M48
; DRILL file {KiCad 7.0.1} date Tue 02 May 2023 22:09:19 BST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-02T22:09:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X5.7717Y-2.4709
X5.7717Y-4.3213
X6.2205Y-2.4709
X6.2205Y-4.3213
T0
M30
